version: '3.8'

services:
  api:
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

# docker-compose -f docker-compose-dev.yml up -d