version: "3.8"

services: 
  opimage-processing-api:
    build: 
      context: ./src/Api
      dockerfile: Dockerfile
    container_name: opimage-processing-api
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - opimage-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: opimage-processing-api-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - opimage-processing-api
    networks:
      - opimage-network
    restart: unless-stopped

networks:
  opimage-network:
    external: true

# docker build ./src/Api -t opimage-processing-api # Api Dockerfile
# docker-compose -f docker-compose-dev.yml up --build -d