version: "3"

services: 
  opimage-api:
    build: ./src/Api
    dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  opimage-proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - opimage-api

# docker-compose -f docker-compose-dev.yml up -d